# Generated by Django 2.1.5 on 2020-06-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='fortfolio_site',
            new_name='portfolio_site',
        ),
    ]
